version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - mynet
    tty: true
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  frontend:
    build:
      context: ./dsc_front_estoque
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
      - db
    networks:
      - mynet
    restart: unless-stopped
    command: bash -c "ng serve --host 0.0.0.0"

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=dsc_estoque
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynet

  backend:
    build:
      context: ./dsc_controleestoque
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=''
      - MYSQL_DB=dsc_estoque
    depends_on:
      - rabbitmq
      - db
    networks:
      - mynet
    restart: unless-stopped
    command: bash -c "java -jar app.jar"

networks:
  mynet:
volumes:
  mysql-data:
  rabbitmq_data: